{{ if .Values.istio }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: health-gateway
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*'
    port:
      name: http
      number: {{ .Values.ingress.port }}
      protocol: HTTP2
{{ end }}
