apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: liveness
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: liveness
