{{ if .Values.istio }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - health-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /healthz
    route:
    - destination:
        host: {{ .Values.name }}
        port:
          number: 80
{{ end }}
